# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import os
import sys

sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__))))
import subscription_pb2 as proto_dot_subscription__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/subscription_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SubscriptionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSubscriptions = channel.unary_unary(
            '/proto.SubscriptionService/GetSubscriptions',
            request_serializer=proto_dot_subscription__pb2.GetSubscriptionsRequest.SerializeToString,
            response_deserializer=proto_dot_subscription__pb2.Subscriptions.FromString,
            _registered_method=True)
        self.ActivateSubscription = channel.unary_unary(
            '/proto.SubscriptionService/ActivateSubscription',
            request_serializer=proto_dot_subscription__pb2.CreateSubscriptionRequest.SerializeToString,
            response_deserializer=proto_dot_subscription__pb2.Subscription.FromString,
            _registered_method=True)


class SubscriptionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSubscriptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateSubscription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetSubscriptions': grpc.unary_unary_rpc_method_handler(
            servicer.GetSubscriptions,
            request_deserializer=proto_dot_subscription__pb2.GetSubscriptionsRequest.FromString,
            response_serializer=proto_dot_subscription__pb2.Subscriptions.SerializeToString,
        ),
        'ActivateSubscription': grpc.unary_unary_rpc_method_handler(
            servicer.ActivateSubscription,
            request_deserializer=proto_dot_subscription__pb2.CreateSubscriptionRequest.FromString,
            response_serializer=proto_dot_subscription__pb2.Subscription.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'proto.SubscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.SubscriptionService', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SubscriptionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSubscriptions(request,
                         target,
                         options=(),
                         channel_credentials=None,
                         call_credentials=None,
                         insecure=False,
                         compression=None,
                         wait_for_ready=None,
                         timeout=None,
                         metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SubscriptionService/GetSubscriptions',
            proto_dot_subscription__pb2.GetSubscriptionsRequest.SerializeToString,
            proto_dot_subscription__pb2.Subscriptions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateSubscription(request,
                             target,
                             options=(),
                             channel_credentials=None,
                             call_credentials=None,
                             insecure=False,
                             compression=None,
                             wait_for_ready=None,
                             timeout=None,
                             metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SubscriptionService/ActivateSubscription',
            proto_dot_subscription__pb2.CreateSubscriptionRequest.SerializeToString,
            proto_dot_subscription__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
