# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/user.proto\x12\x05proto\"%\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\thad_trial\x18\x02 \x01(\x08\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x03\x32h\n\x0bUserService\x12,\n\x0cRegisterUser\x12\r.proto.UserId\x1a\x0b.proto.User\"\x00\x12+\n\x0bGetUserByID\x12\r.proto.UserId\x1a\x0b.proto.User\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=27
  _globals['_USER']._serialized_end=64
  _globals['_USERID']._serialized_start=66
  _globals['_USERID']._serialized_end=86
  _globals['_USERSERVICE']._serialized_start=88
  _globals['_USERSERVICE']._serialized_end=192
# @@protoc_insertion_point(module_scope)
